
import math
from collections import Counter

def calculate_entropy(domain):
    """Calculates the Shannon entropy of a domain string."""
    p, lns = Counter(domain), float(len(domain))
    return -sum( count/lns * math.log(count/lns, 2) for count in p.values())

def is_dga(domain):
    """
    Determines if a domain is likely generated by a DGA based on entropy and length.

    Args:
        domain (str): The domain name to check.

    Returns:
        bool: True if DGA is suspected, False otherwise.
    """
    if not domain:
        return False

    # Remove TLD (e.g., .com, .net)
    parts = domain.split('.')
    if len(parts) > 1:
        domain_body = parts[0]
    else:
        domain_body = domain

    # Heuristics
    length = len(domain_body)
    entropy = calculate_entropy(domain_body)

    # High entropy (randomness) usually indicates DGA
    # Length > 12 and Entropy > 3.5 is a common simple threshold
    if length > 12 and entropy > 3.8:
        return True

    # Extremely long domains are also suspicious
    if length > 25:
        return True

    # Consonant to vowel ratio check could be added here

    return False
