version: '3.8'
services:
  api:
    build: ./docker/api
    ports:
      - "8080:8080"

  ai:
    build: ./docker/ai
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend/nexdefend-frontend
    ports:
      - "3000:3000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: nexdefend
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexdefend_db
    ports:
      - "5432:5432"
