version: "3.8"
services:
  api:
    build:
      context: ../backend/go/nexdefend-api
      dockerfile: /api/Dockerfile
    ports:
      - "8080:8080"

  ai:
    build:
      context: ../backend/python/nexdefend-ai
      dockerfile: /ai/Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build: /frontend/nexdefend-frontend
    ports:
      - "3000:3000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: nexdefend
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nexdefend_db
    ports:
      - "5432:5432"
